print('Введите значения для a')
a = int(input())
print('Введите значение для b')
b = int(input())
print('Введите значение для с')
c = int(input())
q=(a**2 + b**2)
e=(3*b - 4)
t=(4*c**5 / 6)
y=(q / e)
print(y // t)
print(y % t)